export const inventory = {
  "psa:117401741": {
    code: "psa:117401741",
    displayName: "Umbreon V",
    grade: "PSA 10",
    title: "2021 Pokemon Japanese Eevee Heroes #085 FA/Umbreon V",
    subtitle: "Cert #117401741 · Missing Texture",
    heroMeta: "Eevee Heroes (2021) · #085 · Full Art",
    icon: "🌙",
    marketPrice: "$1,240",
    marketRange: "$1,180 to $1,320 weighted from 7 comps",
    trend: "+8.4%",
    trend24h: "+2.1% 24h",
    confidence: "High",
    liquidity: "Fast",
    low30d: "$1,050",
    high30d: "$1,420",
    chartLabels: ["-05", "04-10", "04-15", "04-20", "04-25", "04-30"],
    chartValues: [18, 24, 20, 32, 41, 56, 61, 58, 69],
    comps: [
      {
        source: "eBay",
        price: "$1,225",
        date: "May 3",
        type: "Best Offer",
        note: "2021 Eevee Heroes Umbreon V PSA 10",
      },
      {
        source: "Goldin",
        price: "$1,410",
        date: "Apr 24",
        type: "Auction",
        note: "Umbreon V FA PSA 10 auction close",
      },
      {
        source: "PriceCharting",
        price: "$1,260",
        date: "Daily",
        type: "Guide",
        note: "Product guide benchmark",
      },
      {
        source: "PSA",
        price: "$1,280",
        date: "Recent",
        type: "Estimate",
        note: "PSA estimate and similar certs",
      },
    ],
  },
  "psa:134400879": {
    code: "psa:134400879",
    displayName: "Vaporeon EX",
    grade: "PSA 9",
    title: "2016 Pokemon XY Generations #24 Vaporeon EX",
    subtitle: "Cert #134400879 · Generations",
    heroMeta: "Generations (2016) · #24 · Ultra Rare",
    icon: "🌊",
    marketPrice: "$66",
    marketRange: "$58 to $71 weighted from 6 comps",
    trend: "+3.1%",
    trend24h: "+0.6% 24h",
    confidence: "Medium",
    liquidity: "Moderate",
    low30d: "$54",
    high30d: "$78",
    chartLabels: ["-05", "04-10", "04-15", "04-20", "04-25", "04-30"],
    chartValues: [34, 38, 37, 42, 47, 45, 51, 55, 58],
    comps: [
      {
        source: "PSA",
        price: "$62.79",
        date: "May 4",
        type: "Estimate",
        note: "PSA cert market estimate",
      },
      {
        source: "eBay",
        price: "$70",
        date: "Apr 30",
        type: "Best Offer",
        note: "Vaporeon EX PSA 9 recent close",
      },
      {
        source: "PriceCharting",
        price: "$63",
        date: "Daily",
        type: "Guide",
        note: "PriceCharting current value",
      },
      {
        source: "Fanatics",
        price: "$68",
        date: "Apr 25",
        type: "Fixed",
        note: "Marketplace listing conversion",
      },
    ],
  },
  "raw:charizard-base-4": {
    code: "raw:charizard-base-4",
    displayName: "Charizard",
    grade: "PSA 10",
    title: "1999 Pokemon Base Set #4 Charizard Holo",
    subtitle: "Sleeve ID · Showcase record",
    heroMeta: "Base Set (1999) · #4/102 · Holo Rare",
    icon: "🔥",
    marketPrice: "$18,450",
    marketRange: "Live estimate based on recent comps across eBay, Goldin, PriceCharting, Fanatics & PSA.",
    trend: "+11.8%",
    trend24h: "+3.2% 24h",
    confidence: "High",
    liquidity: "Fast",
    low30d: "$16,200",
    high30d: "$21,000",
    chartLabels: ["-05", "04-10", "04-15", "04-20", "04-25", "04-30"],
    chartValues: [12, 10, 21, 18, 13, 16, 24, 22, 28, 28, 31, 40, 44, 39, 48, 46, 52],
    comps: [
      {
        source: "eBay",
        price: "$18,200",
        date: "May 3",
        type: "eBay",
        note: "1999 Base Set Charizard PSA 10",
      },
      {
        source: "Goldin",
        price: "$21,000",
        date: "Apr 30",
        type: "Goldin",
        note: "Charizard Holo PSA 10 auction",
      },
      {
        source: "Fanatics",
        price: "$17,950",
        date: "Apr 28",
        type: "Fanatics",
        note: "Vault marketplace comp",
      },
      {
        source: "PSA",
        price: "$18,600",
        date: "Recent",
        type: "PSA",
        note: "Similar certs and estimate context",
      },
    ],
  },
};

export function getCardByCode(code) {
  if (!code) {
    return null;
  }

  return inventory[code.trim().toLowerCase()] ?? null;
}
